# Generated by Django 4.1.3 on 2023-01-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MakerSpace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.CharField(max_length=255)),
                ("height", models.IntegerField(default=512)),
                ("width", models.IntegerField(default=512)),
                ("steps", models.IntegerField(default=50)),
                ("seeds", models.IntegerField(default=222222222)),
                ("scale", models.IntegerField(default=7)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Member_space",
            fields=[
                (
                    "picturebook_ID",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("bookshielf_ID", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Picturebook",
            fields=[
                (
                    "picturebook_ID",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("outline", models.CharField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="MakerSpace",
        ),
    ]
