# Generated by Django 4.1.3 on 2023-01-20 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("MakerSpace", "0002_image_member_space_picturebook_delete_makerspace"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Member_space",
        ),
        migrations.RemoveField(
            model_name="picturebook",
            name="picturebook_ID",
        ),
        migrations.AddField(
            model_name="image",
            name="picturebook",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="MakerSpace.picturebook",
            ),
        ),
        migrations.AddField(
            model_name="picturebook",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="image",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="picturebook",
            name="outline",
            field=models.TextField(),
        ),
    ]
