# Generated by Django 4.1.4 on 2023-01-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MakerSpace", "0004_generate_promptbase"),
    ]

    operations = [
        migrations.RenameModel(old_name="Generate", new_name="Category",),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterModelOptions(
            name="promptbase", options={"ordering": ("category", "keyword")},
        ),
    ]
